// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("TicketProblem.Host")]
[assembly: AssemblyProductAttribute("TicketProblem")]
[assembly: AssemblyDescriptionAttribute("Solve ticket problem")]
[assembly: AssemblyVersionAttribute("1.0.1")]
[assembly: AssemblyFileVersionAttribute("1.0.1")]
[assembly: AssemblyConfigurationAttribute("Release")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "TicketProblem.Host";
        internal const System.String AssemblyProduct = "TicketProblem";
        internal const System.String AssemblyDescription = "Solve ticket problem";
        internal const System.String AssemblyVersion = "1.0.1";
        internal const System.String AssemblyFileVersion = "1.0.1";
        internal const System.String AssemblyConfiguration = "Release";
    }
}
