// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("TicketProblem")>]
[<assembly: AssemblyProductAttribute("TicketProblem")>]
[<assembly: AssemblyDescriptionAttribute("Solve ticket problem")>]
[<assembly: AssemblyVersionAttribute("1.0.1")>]
[<assembly: AssemblyFileVersionAttribute("1.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "TicketProblem"
    let [<Literal>] AssemblyProduct = "TicketProblem"
    let [<Literal>] AssemblyDescription = "Solve ticket problem"
    let [<Literal>] AssemblyVersion = "1.0.1"
    let [<Literal>] AssemblyFileVersion = "1.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
